name: task_5
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  logger: ^2.5.0
  elegant_notification: ^2.4.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Rubik_Regular
      fonts:
        - asset: assets/fonts/rubik/Rubik-Regular.ttf

    - family: Rubik_Medium
      fonts:
        - asset: assets/fonts/rubik/Rubik-Medium.ttf

    - family: Rubik_Bold
      fonts:
        - asset: assets/fonts/rubik/Rubik-Bold.ttf

    - family: Rubik_Black
      fonts:
        - asset: assets/fonts/rubik/Rubik-Black.ttf

    - family: Poppins_Regular
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf

    - family: Poppins_Medium
      fonts:
        - asset: assets/fonts/poppins/Poppins-Medium.ttf

    - family: Poppins_Bold
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf

    - family: Poppins_Black
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
